# Generated by Django 3.0.8 on 2020-07-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uername', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=600)),
            ],
        ),
    ]
